var perfUrl = {
    'validateSession'  : 'user/validateSession',
    'getVersion' : 'version',
    'loadAllEmployees'  : urlPrefix+'employee/loadAllEmployees',
    'loadEmployees'  : urlPrefix+'employee/loadEmployees',
    'loadEmployee'     : urlPrefix+'employee/loadEmployee',
    'loadEmployeeById' : urlPrefix+'employee/loadEmployeeById?employeeId=',
    'updateEmployee'   : urlPrefix+'employee/updateEmployee',
    'addEmployee'      : urlPrefix+'employee/addEmployee',
    'loadEmployeeByDesHistory' : urlPrefix+'employee/loadEmployeeByDesHistory/{fromDate}/{toDate}/{designation}',
    'loadDesignations' : urlPrefix+'designation/loadDesignations',
    'loadDesignationById' : urlPrefix+'designation/loadDesignationById?id=',
    'addDesignation'   : urlPrefix+'designation/addDesignation',
    'updateDesignation': urlPrefix+'designation/updateDesignation',
    'deleteDesignation' : urlPrefix+'designation/deleteDesignation',
    'loadProjects' : urlPrefix+'projects/loadProjects',
    'addProject'   : urlPrefix+'projects/addProject',
    'updateProject': urlPrefix+'projects/updateProject',
    'deleteProject': urlPrefix+'projects/deleteProject',
    'loadProjectById' : urlPrefix+'projects/loadProjectById?projectPk=',
    'loadProjectMembersByProjectId' : urlPrefix+'projectmembers/loadProjectMembersByProjectId?projectId=',
    'loadAllProjectMembers' : urlPrefix+'projectmembers/loadAllProjectMembers',
    'loadProjectMemberById' : urlPrefix+'projectmembers/loadProjectMemberById?projectMemberId=',
    'saveProjectMember' : urlPrefix+'projectmembers/saveProjectMember',
    'updateProjectMember' : urlPrefix+'projectmembers/updateProjectMember',
    'deleteProjectMember' : urlPrefix+'projectmembers/deleteProjectMember',
    'importPto' : urlPrefix+'leave/fetchExcel',
    'carryLeaves' : urlPrefix+'leave/carryLeaves/{year}',
    'getCarryLeaves' : urlPrefix+'leave/getCarryLeaves/{year}',
    'applyLeave' : urlPrefix+'leave/applyLeave',
    'loadAllLeaves' : urlPrefix+'leave/loadAllLeaves/{leaveType}/{calYear}',
    'updateLeave' : urlPrefix+'leave/updateLeave',
    'deleteLeave' : urlPrefix+'leave/deleteLeave',
    'loadLeaveById' : urlPrefix+'leave/loadLeaveById?leaveId=',
    'loadMyLeaves' : urlPrefix+'leave/loadMyLeaves/{leaveType}/{calYear}',
    'getLeaveBalance' : urlPrefix+'leave/getLeaveBalance/{leaveType}/{calYear}/{calMonth}',
    'loadLeaveReport': urlPrefix+'leave/loadLeaveReport',
    'loadAllLeaveReport': urlPrefix+'leave/loadAllLeaveReport',
    'loadNotificationCount' : urlPrefix+'notification/loadNotificationCount',
    'reportsLoadBySbu' : urlPrefix+'reportJobTitle/loadBySbu/{fromDate}/{toDate}/{sbu}/{designation}',
    'loadRoles' : urlPrefix+'roles/loadRoles',
    'loadRolesById' : urlPrefix+'roles/loadRolesById?id=',
    'addRoles'   : urlPrefix+'roles/addRoles',
    'updateRoles': urlPrefix+'roles/updateRoles',
    'deleteRoles' : urlPrefix+'roles/deleteRoles',
    'loadComponents' : urlPrefix+'components/loadComponents',
    'loadComponentsById' : urlPrefix+'components/loadComponentsById?id=',
    'addComponent'   : urlPrefix+'components/addComponent',
    'updateComponent': urlPrefix+'components/updateComponent',
    'deleteComponent' : urlPrefix+'components/deleteComponent',
    'saveEmpRoles' : urlPrefix+'emproles/saveEmpRoles',
    'loadNonEmpByRoles' : urlPrefix+'emproles/loadNonEmpByRoles?roleId=',
    'loadEmpByRoles' : urlPrefix+'emproles/loadEmpByRoles?roleId='
};